### ISSUE TITLE
Untar fork/exec /usr/bin/docker: argument list too long

### ISSUE THREAD

**Issue by f4tq** [jwilder/docker-squash#12]
Hi,

Thanks for doing this project1  I am generating an intermediate image due to huge build who's artifacts I remove but leaves my image bloated.

I'm using docker 1.3.2. and a pull of your repo from today.  I was excited to see that docker-squash has shrunken my image from 9.9G to 2.6 but docker is gacking on loading it back in.  I can save/load other images with docker but I think something must happening with the generated json or something.  

Can you point me at a way to troubleshoot this?  Here is my pipeline:

```
sudo docker save 3e8458581665 | sudo docker-squash -verbose -t hhvm_builder_squashed | sudo docker load
                  -snip-
  -  Replacing 3e8458581665 w/ new layer 5eb58410aab4 (/bin/sh -c #(nop) CMD [/bin/bash])
Tarring up squashed layer 327e680e08d5
Removing extracted layers
Tagging 5eb58410aab4 as hhvm_builder_squashed:latest
Tarring new image to STDOUT
Done. New image created.
                  -snip-
  -  c8ce5a628d02 9 seconds /bin/sh -c #(nop) ENV LD_RUN_PATH=/opt/hhvm-dev/rtf/lib:/... 1.024 kB
  -  5eb58410aab4 8 seconds /bin/sh -c #(nop) CMD [/bin/bash] 1.024 kB
Removing tempdir /tmp/docker-squash547210872
2014/12/15 15:44:35 Error: Untar fork/exec /usr/bin/docker: argument list too long

```

FWIW, there is a seemingly unrelated docker issue -- though it is does involve a forthcoming `docker squash` command --  that matches the error I'm getting here.  Have you run into this before?  

Thanks
Chris

**Comment by ddollar** [comment]
I was just able to reproduce this with an image. The same error happens when I just save and re-load the image without squashing.

**Comment by ddollar** [comment]
docker/docker#10426

**Comment by jwilder** [comment]
@ddollar My current workaround is to remove old images on the host.

**Comment by f4tq** [comment]
Wish I could do that but I build 100s of images...
