### ISSUE TITLE
COPY behaves differently than ADD while squashing

### ISSUE THREAD

**Issue by jamusj** [jwilder/docker-squash#16]
The COPY command behaves similarly to ADD in a Dockerfile, yet when squashed, the COPY commands are replaced after the squashed image, while the ADD commands are removed.

Chances are, including a check for COPY on line 591 of export.go will fix it.  For now, I've replaced COPY with ADDs in my Dockerfile.

**Comment by jwilder** [comment]
Fixed by 89e4431
