### ISSUE TITLE
Tagging with private repository names fails with error

### ISSUE THREAD

**Issue by ailjushkin** [jwilder/docker-squash#17]
When tagging output image with `localhost:5000/imgname:tag` the process ends up with fatal error:

FATA[1068] Error: Illegal tag name (5000/imgname): only [A-Za-z0-9_.-] are allowed, minimum 2, maximum 30 in length.

It is possibly a bug with regular expression query.

**Comment by envygeeks** [comment]
That's not a bug, that's an intentional design from the error message.

**Comment by PositiveAlex** [comment]
@envygeeks okay, how can I bypass this ?

**Comment by envygeeks** [comment]
I just tested and `localhost5000/imgname:tag` works.

**Comment by PositiveAlex** [comment]
You meant localhost:5000, not localhost5000 ?

чт, 26 февр. 2015 г. в 13:05, Jordon Bedwell <notifications@github.com>:

**Comment by envygeeks** [comment]
No, I said what I meant.  The colon in the username is not valid.

**Comment by PositiveAlex** [comment]
But the topic about usage of so called "private regostry", when docker
registry is on your server. do pull an image to the local registry, i
should use localhost:<port> as a username. it's the way docker wants to get
an address of private repository.

чт, 26 февр. 2015 г. в 13:35, Jordon Bedwell <notifications@github.com>:

**Comment by PositiveAlex** [comment]
But i'm agree, this is not a big bug. I may just dont use tagging when
squash an image.

чт, 26 февр. 2015 г. в 13:37, Александр Илюшкин <positivealex@gmail.com>:

**Comment by envygeeks** [comment]
That's kinda what we do for private registries, but now that it was clarified I agree it's probably a bug.

**Comment by PositiveAlex** [comment]
Thank you, there's no need to break all the tasks to fix it, the issue is
just for good times

чт, 26 февр. 2015 г. в 13:39, Jordon Bedwell <notifications@github.com>:

**Comment by phjardas** [comment]
+1

We want to squash images before pushing them to our private repository, hence we need the colon in the first part of the tag.

This is our current workaround:

```bash
#!/bin/bash
TAG=$1
TMPTAG="squash-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"
echo "using temporary tag $TMPTAG"

echo "squashing $TAG"
docker save "$TAG" \
  | sudo TMPDIR=/var/run/shm docker-squash -t "$TMPTAG" \
  | docker load

echo "tagging $TMPTAG as $TAG"
docker tag -f "$TMPTAG" "$TAG"

echo "removing temporary tag $TMPTAG"
docker rmi "$TMPTAG"

echo "done."
```

**Comment by twllight** [comment]
+1 on this as well we're using a work around on this as well would be great to not have it fail for the colon!

**Comment by jperville** [comment]
+1 on this also, docker-squash should not generate unloadable images because of the way the tag argument is parsed.

**Comment by PositiveAlex** [comment]
@envygeeks four people agreed it's a bug :) maybe you change the status from `probably a bug` to `a bug`? ;)

**Comment by envygeeks** [comment]
I'm not a maintainer on this repository or I would.

**Comment by PositiveAlex** [comment]
@envygeeks okay...
