### ISSUE TITLE
Squashed image is different from original

### ISSUE THREAD

**Issue by tescalada** [jwilder/docker-squash#23]
I am new to docker so I may be doing something wrong here, but as far as I can tell, something is being lost in the squashing process.

I am squashing an image based in python:2.7 and after the squash python is broken. 

The difference between the two images seems to be that the squashed image is missing the python2.7 dir in /usr/local/lib/

Steps to reproduce:

```bash
# setup
docker pull python:2.7

# squash
docker save `docker inspect --format '{{ .Id }}' python:2.7` | sudo docker-squash -verbose -t python:squash | docker load

# make sure it works pre-squash
docker run -it python:2.7 python -c 'print "it works"'

# show it fails post-squash
docker run -it python:squash python -c 'print "it works"'

# good one has /usr/local/lib/python2.7 
docker run -it python:2.7 ls -alh /usr/local/lib/

# squashed one doesn't
docker run -it python:squash ls -alh /usr/local/lib/
```

**Comment by jwilder** [comment]
Hey Tristan.  That `python:2.7` image has a `apt-get purge python.*` line in it's history.  That is removing `/usr/local/lib/python2.7`. Later on, it has a `pip install virtualenv` line which re-install python2.7 in the same location.

There seems to be an issue where the previous delete is overwriting a newer writes to the same location.  Deletes in docker images don't really delete anything an just hide the in later layers.  I think how `docker-squash` is deleting whiteouts is not quite right in this case.  It should only delete files that have modification date older than the whiteout files date.

**Comment by agaffney** [comment]
I think that I'm running into something similar. I have an image deletes some files in /etc/yum.repos.d/ as one of the earlier steps in the Dockerfile. When I run it through docker-squash, those files are back. I double-checked that they do NOT exist in the source image.

**Comment by twllight** [comment]
+1 on this as well. it seems that when certain packages are installed ( such as vim ) the vim binary goes missing inside of the container after a squash.

**Comment by orls** [comment]
I'm investigating how docker squashing works , and understanding the docker layer format. I was curious about deletions and did some tests. In short, the way this project manages deletions is incorrect.

@jwilder you're correct to say that
> I think how docker-squash is deleting whiteouts is not quite right in this case.

However, you then say...

> It should only delete files that have modification date older than the whiteout files date.

I'd really advise against doing this, I feel like file-modification date is not reliable for detecting these cases. There's a better way, anyway:

The code currently unpacks [every layer, in order](https://github.com/jwilder/docker-squash/blob/master/export.go#L500), into a temporary directory, and then does a sweep at the end [finding `.wh.` files](https://github.com/jwilder/docker-squash/blob/master/export.go#L507) ('whiteout
 files, docker's internal marker for a deleted file) and deleting them if present.

This means that if you delete a file in layer N, then add it again in a later layer M, there will be a 'stale' `.wh.` file -- docker squash will delete the file that you re-added!

I can imagine this causing a ton of pain with things like package manager files :scream: 

The solution, I think, is to sweep for `.wh.` files per-layer -- making sure that all .wh. are removed, before the next layer, even if they don't point to anything.

**Comment by chnrxn** [comment]
I'm having the same problem that the squashed image has files that are supposed to be deleted. As a result I had to stop squashing the image because I really needed one of those files to be gone.

I think a good sanity test for this utility would be to check that the files in the final squashed image are the same as that in the final original image!

**Comment by adfernandes** [comment]
I just got bit by this one. I had something along the lines of
```
RUN  mv /etc/foo /etc/foo.backup
COPY bar /etc/foo
```
but the final squashed image only had `/etc/foo.bakcup`, no `/etc/foo`.

**Comment by jwilder** [comment]
@orls Went with you suggestion of removing whiteouts after extracting each layer.  Thanks!
@tescalada Thanks for the repro steps!

**Comment by adfernandes** [comment]
Works for me... :+1: Thank you!

**Comment by chnrxn** [comment]
@jwilder A file that I deleted in the Dockerfile actually came back in the squashed image. In fact, on the image that I squashed, the squashed image had a few hundred files more than the un-squashed one.

This happens even on v0.2.0. 

Dockerfile:

    from oraclelinux:6
    run rm -vf /etc/yum.repos.d/public-yum-ol6.repo

1. build with `docker build -t original . `
2. squash _original_ to _squashed_

Testing:

`docker run --rm original ls /etc/yum.repos.d`

`docker run --rm squashed ls /etc/yum.repos.d`

**Comment by jwilder** [comment]
@chnrxn Try adding `-from root` to your squash step.

**Comment by chnrxn** [comment]
@jwilder that works, but then that also takes away the base layer, which I would really like to keep. Is there no way of ensuring that files stay removed without forcing a `-from root`?

**Comment by jwilder** [comment]
@chnrxn In this case, you would need to squash the base image and use that as your base image. Squashing will only remove files added and removed after the base image unless you specify -from root.
