### ISSUE TITLE
Configuration commands can be combined

### ISSUE THREAD

**Issue by rpendleton** [jwilder/docker-squash#26]
Some of the configuration commands can be combined into single commands (or removed). I'm not sure if this is something we'd want to do for all of them, but it can certainly remove some layers. For example, the following two docker files are equivalent:

7 Layers:

``` dockerfile
FROM ubuntu:14.04.2

CMD command_one

ENV env_one=1
ENV env_two=2
ENV env_three=3
ENV env_four=4

CMD command_two
CMD command_three
```

Two Layers:

``` dockerfile
FROM ubuntu:14.04.2

ENV env_one=1 \
    env_two=2 \ 
    env_three=3 \
    env_four=4

CMD command_three
```

**Comment by adfernandes** [comment]
:+1:

**Comment by jwilder** [comment]
True.  These layers are pretty small though so not sure what the benefit would be off-hand.  Would the main benefit be to just cut down on remote pulls for tiny layers?

**Comment by adfernandes** [comment]
He huge benefit is simply the reduction in layers when building. I am doc arising some fairly complex server apps, and for various reasons each container has several processes in it. It is amazingly easy to hit the 127 layer limit!

**Comment by jwilder** [comment]
Ah... makes sense.  That's a lot of layers.

**Comment by adfernandes** [comment]
Yes.

I understand that Docker _usually_ goes with the "one process per container" vibe, but... sometimes it's just way easier to stick all the interdependent processes together.

That way Docker just acts like a VM, but _without_ the requirement to manage virtual hardware. Which is awesome.

But which still makes it really easy to hit the 127 layer limit. :cry:
