### ISSUE TITLE
A bit hard to build

### ISSUE THREAD

**Issue by bean5** [jwilder/docker-squash#33]
I followed the instructions, but I think they were unclear or didn't work. Instead of a `docker-squash` binary, I got a `docker-squash.git` binary. This project shows promise, but could be easier to build. a `docker-compose.yml` file might help out. 

I followed the instructions in `osx_install.md`.

See also https://github.com/jwilder/docker-squash/issues/34

**Comment by jwilder** [comment]
Sorry about that.  You followed the instructions in the `Development` section of the realm?  There are also some pre-compiled releases here: https://github.com/jwilder/docker-squash/releases.  What OS/platform are you using?

**Comment by jwilder** [comment]
Ah... just noticed the `osx_install.md` reference in you desc.

**Comment by bean5** [comment]
Wow, you are a fast responder. I am using `OS X Yosemite 10.10.3`.

**Comment by jwilder** [comment]
I've added an OSX binary to the release pages.

**Comment by bean5** [comment]
Awesome!
