### ISSUE TITLE
osx_install.md could be updated

### ISSUE THREAD

**Issue by bean5** [jwilder/docker-squash#35]
It could mention that there is a binary release at https://github.com/jwilder/docker-squash/releases

**Comment by bean5** [comment]
I suppose also the main README.md could list a way to download and install via CLI, if possible.

**Comment by webRat** [comment]
In osx_install.md:
`go get github.com/docker/docker/pkg/units` <-- doesn't exist anymore in the

**Comment by jwilder** [comment]
I think that file is not needed anymore.  You should be able to use these instructions: https://github.com/jwilder/docker-squash#development

**Comment by bean5** [comment]
If that is the case, go ahead and close this. I won't be able to verify anytime soon, myself. Great project idea, nevertheless!
