### ISSUE TITLE
docker-squash without sudo

### ISSUE THREAD

**Issue by palamccc** [jwilder/docker-squash#44]
Is it possible to use docker-squash without sudo, i'm trying to write a script to build our web app, and trying to add docker-squash to the bash script. But its failing without sudo. All the examples in the project README.md are also with sudo. Is there any workaround to use docker-squash without sudo ?

**Comment by cs278** [comment]
I'm attempting to use this with `fakeroot` which should alleviate the need to give it root permissions, but there are hard coded calls to `sudo` which prevent me from testing this.

I can see the reason to use `sudo` within the code so you only elevate privileges when required, would it be possible to check if the process is running as root and not use sudo?

```
export.go:535:    cmd := exec.Command("sudo", "/bin/sh", "-c", "tar cOf  - *")
image.go:83:  cmd := exec.Command("sudo", "/bin/sh", "-c", "tar cvf ../layer.tar ./")
```

**Comment by yuecelm** [comment]
This solution worked for me without using sudo: https://github.com/jwilder/docker-squash/pull/15

I compiled from rafecolton the integrate-libsquash branch once, here is my linux/x86-64 build:
[docker-squash-libsquash.zip](https://github.com/jwilder/docker-squash/files/102617/docker-squash-libsquash.zip)

**Comment by jbakosi** [comment]
@yuecelm I tried the libsquash version but tagging does not seem to work. I tried `-t <tag>` and `-t=<tag>`. Is there something I'm missing?

**Comment by yuecelm** [comment]
I am not sure if I tried tagging with docker-squash(-libsquash). but you tried 'docker tag <image id> <name>' after image load? this should work in any case...

**Comment by jbakosi** [comment]
It generates the image fine, but does not tag it. Then I can tag by `docker tag <hash>`, but in a script I want to use this in, I don't have access to the <hash> easily. The non-libsquash version tags it fine.

**Comment by yuecelm** [comment]
have you tried this branch: https://github.com/winchman/libsquash/tree/add-tag-and-from-options ?

**Comment by jbakosi** [comment]
I have finally got around trying this. It seems like there is a bunch of forks of docker squash and I have successfully ran (without sudo) the fork at https://github.com/goldmann/docker-squash, after installed it with `pip install docker-squash`.
