### ISSUE TITLE
Silently fails with Docker 1.10RC2

### ISSUE THREAD

**Issue by marius311** [jwilder/docker-squash#45]
I tried with Docker [1.10RC2](https://github.com/docker/docker/releases/tag/v1.10.0-rc2) and there's no error messages but in the end I don't seem to get a new image created. I'm using this form:

``` bash
docker save img | docker-squash -t img-squashed | docker load
```

Any ideas to make it work? We regularly use `docker-squash` to deploy apps at [Cosmology@Home](https://github.com/marius311/cosmohome) so it'd be great to keep it working.

**Comment by jwilder** [comment]
You could try running w/ `-verbose`.  That might reveal something.  I have not tried docker 1.10RC2 so no idea what might have changed that would break it.

**Comment by marius311** [comment]
My image `test` looks like this:

```Dockerfile
FROM debian:latest
RUN true
RUN true
```

and I get this:

```
$ docker save test | sudo docker-squash -verbose -t test-slim | docker load
Loading export from STDIN using /tmp/docker-squash154642662 for tempdir
Loaded image w/ 2 layers
  -  test (1 tags)
Extracting layers...
  -  /tmp/docker-squash154642662/2c65e251db25bc1f327bf1e43e882893a6f7fd807d7091b0f3776cbbdf20431d/layer.tar
  -  /tmp/docker-squash154642662/e61c489c973d05149002e5ba9ce56a148dd143dad044215b34b8727972f905d1/layer.tar
Inserted new layer 5b7077e499c5 after 2c65e251db25
  -  2c65e251db25 
  -> 5b7077e499c5 /bin/sh -c #(squash) from 2c65e251db25
  -  e61c489c973d /bin/sh -c true
Squashing from 5b7077e499c5 into 5b7077e499c5
  -  Deleting whiteouts for layer e61c489c973d
  -  Rewriting child history
  -  Removing e61c489c973d. Squashed. (/bin/sh -c true)
Tarring up squashed layer 5b7077e499c5
Removing extracted layers
Tagging 5b7077e499c5 as test-slim:latest
Tarring new image to STDOUT
Done. New image created.
  -  2c65e251db25 292.471209 years  130.9 MB
  -  5b7077e499c5 Less than a second /bin/sh -c #(squash) from 2c65e251db25 10.24 kB
Removing tempdir /tmp/docker-squash154642662
```

but at this point neither `5b7077e499c5` nor `test-slim:latest` exit.

**Comment by jwilder** [comment]
Looking at the 1.10 release notes, they changed the image format to a content addressable model. That is probably what is causing this breakage.

**Comment by jmorcar** [comment]
marius311 - I try the comand in docker 1.8.2 and it's OK:

sudo docker save fe84118a61b0 | sudo ./docker-squash -t squash -verbose | sudo docker
This creates a new image named squash:
[zenoss@PZENOSS01 ~]$ sudo docker images
REPOSITORY TAG IMAGE ID CREATED VIRTUAL SIZE
squash latest 2c9a698188f1 45 hours ago 1.856 GB
localhost:5000/48vf9rbm58ec5vhj4wm27t2gq/core_5.0 20151202-100510 bf31c04a55ba 8 weeks ago 2.591 GB
localhost:5000/48vf9rbm58ec5vhj4wm27t2gq/core_5.0 20160119-020010 fe84118a61b0 8 weeks ago 2.588 GB
localhost:5000/48vf9rbm58ec5vhj4wm27t2gq/core_5.0 20160126-020008 fe84118a61b0 8 weeks ago 2.588 GB
localhost:5000/48vf9rbm58ec5vhj4wm27t2gq/core_5.0 20151223-020011 fe84118a61b0 8 weeks ago 2.588 GB
localhost:5000/48vf9rbm58ec5vhj4wm27t2gq/core_5.0 20160115-020011 fe84118a61b0 8 weeks ago 2.588 GB
localhost:5000/48vf9rbm58ec5vhj4wm27t2gq/core_5.0 20160106-020010 fe84118a61b0 8 weeks ago 2.588 GB
localhost:5000/48vf9rbm58ec5vhj4wm27t2gq/core_5.0 20160124-020010 fe84118a61b0 8 weeks ago 2.588 GB


it is valid to squash app Zenoss.core. Now I tested to do new history changes and nothing error is displayed about layers.

Furthermore, If you do the command,
docker history localhost:5000/48vf9rbm58ec5vhj4wm27t2gq/core_5.0
Now shows very few lines (layers) and one line says #(squash) from 8efe4.......

I hope it helps you.

**Comment by jmorcar** [comment]
Sorry one question about, when you squash images, I have a lot of docker images are tagged from "weeks ago", "years ago"... 
Is correct this? Or Is there any procedure to remove old tagged images without data loss ?

I have see this command to remove old containers but, not tagged images:
$ docker ps -a | grep 'weeks ago' | awk '{print $1}' | xargs --no-run-if-empty docker rm

My particular case is that Zenoss core image has multiple subtree layers with dependency..... (squash command was fine with this)  but my suspicion is that a possible RM command should remove actual data are not obsolete.

**Comment by mike227** [comment]
Hi, is there any progres? Exists some solution how to use docker-squash with docker 10.10?

**Comment by ronaldtse** [comment]
+1 Looking forward to having docker-squash work with 10.10. Any news?

**Comment by jwilder** [comment]
I'm not working on this, but a PR to fix it would be welcome.

**Comment by tslater** [comment]
+1

**Comment by CpuID** [comment]
Confirmed, same behaviour on Docker 1.10.2 (Linux). I suspect @jwilder is right and the content addressable images stuff is a big factor.

**Comment by marius311** [comment]
In lieu of a fix here, does anyone know of any similar tools compatible with Docker 1.10+? Seems like docker-slim is similar but doesn't really let you control exactly what to squash. (of course +1 for a fix here, that would be ideal)

**Comment by amoghe** [comment]
I started investigating what would be needed for a fix, here's what I read up on:

1. a migrator tool was released when the change was made, but it only works on graph root dirs (https://github.com/docker/v1.10-migrator)
2. A pkg exists (docker/docker/migrate/v1) that exposes a calculate checksum function (https://godoc.org/github.com/docker/docker/migrate/v1) though I havent closely looked at what it operates on. Presumably this is useful for renaming old layer dirs to have the SHA256 hash of the content instead. This is the crux of the Content Addressable Storage change in docker v1.10
3. The `repositories` file is seemingly deprecated in favor of a new `manifest.json` but it continues to be created in new tarballs for backward compatibility. I cannot seem to find the specification for the format of the `manifest.json` file.

I'm wont be able to dedicate a lot of time to this for the next few weeks. If someone else is able to, I hope the pointers above help.

**Comment by georgevreilly** [comment]
We've been using docker-squash in our build, which has been breaking this week, as squashed images don't get loaded back into Docker. I'm surprised that we didn't hit this earlier since Docker 1.10 has been out for a couple of months. Our build pulls the latest Ubuntu 14.04 package from the Docker repository.

**Comment by haliphax** [comment]
Also suffering from this on 1.11.2 :(

**Comment by ronaldtse** [comment]
Actually we have changed our flow to use another docker-squash (below) it's much faster and works with docker 1.10+!
https://github.com/goldmann/docker-squash/
