### ISSUE TITLE
Why would you not do cleanup in dockerfile

### ISSUE THREAD

**Issue by donniev** [jwilder/docker-squash#46]
This is really not an issue just a question.
I usually do the cleanup of removing directories etc in my DockerFile.
Is there a disadvantage to doing it there instead of doing it manually after the image is built?

**Comment by sundbry** [comment]
If you just clean up at the end of your Dockerfile, the intermediate images still have to get built and pushed, so you end up still having to transfer the files you cleaned out.

**Comment by guy4261** [comment]
`$ docker build .` the following `Dockerfile`:

```Dockerfile
FROM foo
COPY bigfile
RUN rm bigfile
```

You will see that the resulting image is much `sizeof(bigfile)` larger than `foo`, even though you deleted it.
