### ISSUE TITLE
docker/docker/pkg/units not found

### ISSUE THREAD

**Issue by donniev** [jwilder/docker-squash#50]
Trying to install on Mac El Cap
units does not appear to be in the docker/docker/pkg repo

TheBeast:nodecontainerbuddybase donvawter$ go get github.com/docker/docker/pkg/units
package github.com/docker/docker/pkg/units: cannot find package "github.com/docker/docker/pkg/units" in any of:
        /usr/local/Cellar/go/1.5.3/libexec/src/github.com/docker/docker/pkg/units (from $GOROOT)
        /Users/donvawter/.go/src/github.com/docker/docker/pkg/units (from $GOPATH)

**Comment by jwilder** [comment]
Are you following the [development instructions](https://github.com/jwilder/docker-squash#development)?  You need to use `glock` to pull dependencies.

**Comment by anlek** [comment]
Yes, but if you look at docker/docker/pkg, units is no longer a folder that's there...https://github.com/docker/docker/tree/master/pkg

**Comment by enryold** [comment]
I solved by creating an empty directory in my .go home folder, than copying 4 files from here 
https://github.com/aduermael/minecraft-docker-client/tree/master/go/src/github.com/docker/docker/pkg/units


`mkdir -p /Users/enryold/.go/src/github.com/docker/docker/pkg/units`
`cp /Users/enryold/Downloads/*.go /Users/enryold/.go/src/github.com/docker/docker/pkg/units/`

**Comment by mtakaki** [comment]
Thanks, @enryold! This worked for me!

**Comment by jwilder** [comment]
@anlek You are linking to master which is not the correct commit that this project uses.  See the `GLOCKFILE` in the root of the project.

You should be able to run `glock sync github.com/jwilder/docker-squash` as described in [development instructions](https://github.com/jwilder/docker-squash#development).  That will checkout all the dependencies with the correct versions into your `$GOPATH`.  This project depends on [docker/docker@2606a2](https://github.com/docker/docker/tree/2606a2e4d3bf810ec82e373a6cd334e22e504e83) which contains the [pkg/units](https://github.com/docker/docker/tree/2606a2e4d3bf810ec82e373a6cd334e22e504e83/pkg/units).
