### ISSUE TITLE
Error in setting up env to compile on Mac.

### ISSUE THREAD

**Issue by wpoosanguansit** [jwilder/docker-squash#52]
I followed the instruction to compile the code on Mac but I am still having the issue of not being able to get the units.  I saw a post mentioning synching using glock.  So I installed glock and ran the command:

open ~/.go/src/github.com/jwilder/docker-squash/GLOCKFILE: no such file or directory

It still gave me an error.  Do I need to clone the project into .go folder?  I am just not sure if that is supposed to be the case.  Thanks for your help.

**Comment by jwilder** [comment]
Yes. Clone the project.
