### ISSUE TITLE
loading .tar via cat squashed.tar | docker load , docker images shows no new reduced size image

### ISSUE THREAD

**Issue by sivang** [jwilder/docker-squash#53]
Ubuntu 14.04 on Amazon EC2

followed instructions here:
https://github.com/jwilder/docker-squash

**Comment by bmaltais** [comment]
Try:

tar --delete -f squashed.tar manifest.json

then

cat squashed.tar | docker load

**Comment by navad** [comment]
We created https://github.com/jwilder/docker-squash/pull/55 which solves this issues and adds basic support for the new docker manifest file. Hope it helps
