### ISSUE TITLE
Squashed image not rerunning the image history

### ISSUE THREAD

**Issue by YerisAntonio** [jwilder/docker-squash#57]
Extracting layers...
-  /tmp/docker-squash184390964/53b8e727e33ca37e5a9938107bd6b030c5c18804a1cdf145ebb5b37efa57c15a/layer.tar
-  /tmp/docker-squash184390964/57fdabbcbbd733d21a5f4f764102ad9fdc3523289cf8faf7e3bb55e180e11c80/layer.tar
-  /tmp/docker-squash184390964/5d5dc6a600125e54bfb94f3ea1e5ed401b7cd84263ba29d05092a9d75a0bb07d/layer.tar
-  /tmp/docker-squash184390964/7397b069ec3e2327b89cd45c6172dbdf543876947678b1fc48cbc9829ca426ee/layer.tar
-  /tmp/docker-squash184390964/b5ae67ec3dcb6288dd181642ec57f00acb51422638b239119c405283b1fd2e16/layer.tar
-  /tmp/docker-squash184390964/faa7ad651836c42be41ef3ebb36358e116cef1d996251431e1b0fc64dc6021cc/layer.tar
-  /tmp/docker-squash184390964/2587e40a84bfd5c037e735d2913444a010d33a41931245b6a3c7b83718c66783/layer.tar
-  /tmp/docker-squash184390964/27a7e9df4b42ff368c7541849df3479f88d4c1c91d617c3cd8a30e0705c77ca3/layer.tar
-  /tmp/docker-squash184390964/f61d7ac5814b84215efff3569417ca8ee50d7688b82802355a9187d570f78a76/layer.tar
-  /tmp/docker-squash184390964/48863186f5e0baef52a091fdf45962a95a2e2c99582cda7640ac93fe6441a275/layer.tar
-  /tmp/docker-squash184390964/b0a16415dc07708bf06923be992a374c91fc067c46a2e3dfba3b26cb7cbec2f8/layer.tar
  Inserted new layer fcb5419f383b after 5d5dc6a60012
-  5d5dc6a60012 
  -> fcb5419f383b /bin/sh -c #(squash) from 5d5dc6a60012
-  48863186f5e0 
-  57fdabbcbbd7 
-  53b8e727e33c 
-  b0a16415dc07 
-  f61d7ac5814b 
-  7397b069ec3e 
-  2587e40a84bf 
-  27a7e9df4b42 
-  faa7ad651836 
-  b5ae67ec3dcb /bin/sh -c apk del gcc g++ linux-headers paxctl gnupg && rm 
  Squashing from fcb5419f383b into fcb5419f383b
-  Deleting whiteouts for layer 48863186f5e0
-  Deleting whiteouts for layer 57fdabbcbbd7
-  Deleting whiteouts for layer 53b8e727e33c
-  Deleting whiteouts for layer b0a16415dc07
-  Deleting whiteouts for layer f61d7ac5814b
-  Deleting whiteouts for layer 7397b069ec3e
-  Deleting whiteouts for layer 2587e40a84bf
-  Deleting whiteouts for layer 27a7e9df4b42
-  Deleting whiteouts for layer faa7ad651836
-  Deleting whiteouts for layer b5ae67ec3dcb
-  Rewriting child history
-  Removing 48863186f5e0. Squashed. ()
-  Removing 57fdabbcbbd7. Squashed. ()
-  Removing 53b8e727e33c. Squashed. ()
-  Removing b0a16415dc07. Squashed. ()
-  Removing f61d7ac5814b. Squashed. ()
-  Removing 7397b069ec3e. Squashed. ()
-  Removing 2587e40a84bf. Squashed. ()
-  Removing 27a7e9df4b42. Squashed. ()
-  Removing faa7ad651836. Squashed. ()
-  Removing b5ae67ec3dcb. Squashed. (/bin/sh -c apk del gcc g++ linux-headers paxctl...)
  Tarring up squashed layer fcb5419f383b

**Comment by YerisAntonio** [comment]
Image history

b05b63031b69        About an hour ago   /bin/sh -c apk del gcc g++ linux-headers paxc   282.4 kB            
8e7ec1e8d739        About an hour ago   /bin/sh -c #(nop) CMD ["npm" "run" "start-pro   0 B                 
a9e90905b425        About an hour ago   /bin/sh -c #(nop) EXPOSE 3000/tcp 8080/tcp      0 B                 
cd1d69aae365        About an hour ago   /bin/sh -c #(nop) ENV SERVICE_8080_NAME=image   0 B                 
a498a98b67a3        About an hour ago   /bin/sh -c #(nop) ENV SERVICE_3000_NAME=image   0 B                 
8623a2ce1b7d        About an hour ago   /bin/sh -c #(nop) COPY dir:51e3e12e123da4640b   31.59 kB            
1a8f4f0402e4        About an hour ago   /bin/sh -c npm install                          116 MB              
262101f0a7f0        About an hour ago   /bin/sh -c #(nop) COPY file:548267170fc8d7bd7   69 B                
5ce0a37618a5        About an hour ago   /bin/sh -c #(nop) COPY file:c9dbe68eec9593b8d   3.805 kB            
04661c4df41e        About an hour ago   /bin/sh -c #(nop) WORKDIR /usr/src/app          0 B                 
9aca65ac4777        About an hour ago   /bin/sh -c #(nop) ENV RM_DIRS=/usr/include      0 B                 
f62dc7486e89        About an hour ago   /bin/sh -c #(nop) ENV VERSION=v5.7.1 NPM_VERS   0 B                 
b7a6016eaf9a        About an hour ago   /bin/sh -c npm install                          115.5 MB            
f417b0675645        About an hour ago   /bin/sh -c #(nop) COPY file:548267170fc8d7bd7   69 B                
b0a433b2c348        About an hour ago   /bin/sh -c #(nop) COPY file:21669b97bfbcbcc70   1.863 kB            
4346c93ebb51        About an hour ago   /bin/sh -c #(nop) WORKDIR /usr/src/app          0 B                 
1c98a49ae88f        About an hour ago   /bin/sh -c mkdir -p /usr/src/app                0 B                 
fd92c7bdd213        About an hour ago   /bin/sh -c #(nop) ENV TERM=xterm                0 B                 
2b486887f545        About an hour ago   /bin/sh -c apk add --no-cache curl make gcc g   500.5 MB            
21e040efde3d        About an hour ago   /bin/sh -c #(nop) ENV VERSION=v5.7.1 NPM_VERS   0 B                 
f70c828098f5        12 days ago         /bin/sh -c #(nop) ADD file:701fd33a2f463fd4bd   4.799 MB

**Comment by YerisAntonio** [comment]
Docker version 1.10.3, build 20f81dd

**Comment by pompomJuice** [comment]
Same issue

**Comment by YerisAntonio** [comment]
Use the docker-squash that comes with pip, it is the one that works just fine, this one I think its not longer maintained.

**Comment by zot** [comment]
This works for me without using docker-squash:

1. Make a container that changes the image as in the normal docker-squash instructions
2. use `docker export CONTAINER-ID | docker import - REPOSITORY:TAG` to produce the squashed image

As far as I can tell, this produces an image similar to what docker-squash would produce.
