### ISSUE TITLE
Cannot mkdir: No space left on device

### ISSUE THREAD

**Issue by liuxiaopiao** [jwilder/docker-squash#58]
When I use the docker squash to reduce my docker image size with the command "docker save  | sudo docker-squash -t newtag | docker load", I met the problem such like 
tar: home/work_87586/dbzip_shiphome: Cannot mkdir: No space left on device

And my image size is 26.45G. 
Here is the details info of my container(which run from the image which I want to reduce size) 
[root@f7ece21 /]# df -h
Filesystem Size Used Avail Use% Mounted on
/dev/loop0 100G 29G 71G 29% /
tmpfs 7.3G 0 7.3G 0% /dev
shm 64M 0 64M 0% /dev/shm
tmpfs 7.3G 0 7.3G 0% /sys/fs/cgroup
/dev/loop0 100G 29G 71G 29% /etc/hosts

How can i fix this kind of problem?

**Comment by liuxiaopiao** [comment]
Fix the problem by declaring the TMPDIR .

**Comment by mcraveiro** [comment]
I had a similar problem, but I was using sudo on a normal shell. In this case, there is a small gotcha: you can't just ```export TMPDIR=...``` and then sudo as the variable will not be defined for root. Instead, do as per README:

```
$ docker save <image_id> | sudo TMPDIR=/var/run/shm docker-squash -t newtag | docker load
```
(or su and export the variable as root then run the command).

**Comment by andrewssobral** [comment]
I had a similar problem, my docker image is 15Gb and I have 32Gb of RAM (where only 2Gb is used):
```
# REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
# activeeon/dlm3      latest              c52f78190064        4 weeks ago         15.2GB

# docker save c52f78190064 | sudo TMPDIR=/var/run/shm ./docker-squash -from root -t activeeon/dlm3:squashed | docker load
```

The output is:
```
...
tar: root/visdom/visdom.egg-info/dependency_links.txt: Cannot write: No space left on device
tar: root/visdom/visdom.egg-info/not-zip-safe: Cannot write: No space left on device
tar: root/visdom/visdom.egg-info/requires.txt: Cannot write: No space left on device
tar: root/visdom/visdom.egg-info/top_level.txt: Cannot write: No space left on device
tar: root/visdom/webpack.config.js: Cannot write: No space left on device
tar: root/visdom/yarn.lock: Cannot write: No space left on device
tar: Exiting with failure status due to previous errors
ERROR: exit status 2
open /var/lib/docker/tmp/docker-import-927136952/repositories: no such file or directory

$ free -m
              total        used        free      shared  buff/cache   available
Mem:          32109        2113       24614          95        5381       29349
Swap:         32705          11       32694
```
This error occurs when the program exceeds 15Gb of RAM (50% of the Total).
There exist a memory limitation or I'm doing something wrong? Thanks!
