### ISSUE TITLE
Is docker-squash abandoned?

### ISSUE THREAD

**Issue by ryenus** [jwilder/docker-squash#62]
Dear @jwilder and/or related, are we still going to move this forward?

I tried to fix the build issue with package `[go-]units`, in the hope of making it into Homebrew, but found out several people having been dealing with it according to a number of latest pull requests (#55, #48) . But none of them is merged or actively followed. The same applies to issues, so does the commit history, which was [last updated][1] half a year ago.

Let's try to be positive, maybe someone capable can lend a hand?

[1]: https://github.com/jwilder/docker-squash/commit/d78be897bab28dc6419d89178f841fae2ecb0412

**Comment by jwilder** [comment]
Nope, not abandoned.  If you are following the [Development](https://github.com/jwilder/docker-squash#development) section, there should not be a build issue.  You need to install `glock` which is the dependency manager used by this project.  If you simply `go get -u ./...`, it will fail to compile, but that is the wrong way to build this project.

When you run `glock sync github.com/jwilder/docker-squash`, it will checkout the appropriate version of the docker repo that has the current packages used by this project and allows you compile correctly.
