### ISSUE TITLE
Unable to squash

### ISSUE THREAD

**Issue by IgorGanapolsky** [jwilder/docker-squash#67]
Hello,
I am running this command on Mac OS Sierra:
`sudo docker-squash -i igorganapolsky.tar -o igorganapolsky-squashed.tar`

However, I get this error:
> tar: Option --xattrs is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
ERROR: exit status 1

What is causing this?

Thanks,
igor

**Comment by jwilder** [comment]
You need to install GNU tar 1.27 or later.

**Comment by IgorGanapolsky** [comment]
So **bsdtar 2.8.3** is not sufficient?

**Comment by jwilder** [comment]
No.  See dependencies section: https://github.com/jwilder/docker-squash#installation

**Comment by IgorGanapolsky** [comment]
@jwilder Thanks.  @changetip $1

**Comment by changetip** [comment]
Hi @jwilder, @IgorGanapolsky sent you a tip worth 1,395 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/954605)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
