### ISSUE TITLE
Docker-squash doesn't work

### ISSUE THREAD

**Issue by mjablecnik** [jwilder/docker-squash#72]
Hello I have docker version: Docker version 17.03.1-ce, build c6d412e
And when I run;
`docker save whoami:latest | sudo docker-squash -t whoami:squashed2 | docker load`

It return me: `Loaded image: whoami:latest`
but whoami:squashed2 is not there
and image  whoami:latest is not squashed..

**Comment by ideahitme** [comment]
@Applemann I can verify having the same issue. 

It is however possible to use `docker import`. Though I am not sure if this satisfies your requirements.

**Comment by xingxiuyi** [comment]
I can verify having the same issue.

**Comment by wxjeacen** [comment]
I can verify having the same issue as well. Hope can fix it ASAP.

**Comment by koustabhdolui** [comment]
Hi, I am having the same issue. 
docker-squash does its job, and squashes the image.
...
Tagging 0270405f60a4 as newtag:latest
Tarring new image to squashed.tar
Done. New image created.
  -  9e3a53cf322d 22 hours  111.1 MB
  -  0a7335bb3acf 9 seconds /bin/sh -c #(squash) from 9e3a53cf322d 766.2 MB
  -  0270405f60a4 3 seconds /bin/sh -c #(nop)  CMD ["bash" "/usr/src/app/scripts/star... 2.81 MB
Removing tempdir /tmp/docker-squash987557424
...

I tried the following things:
1. docker load through STDIN -> the image does not show up
2. docker load --input squashed.tar -> the image does not show up
3. Remove the image from docker and then try to load the new squashed image, results in the same error as @wxjeacen reported.

**Comment by koustabhdolui** [comment]
@ideahitme Your idea indeed hit me!
It works with docker import. Thank you!

**Comment by vvuk** [comment]
It doesn't really work with `docker import`, unless you consider manually untarring the squashed layer and then importing.

The problem seems to be that docker-squash is not actually rewriting the JSON metadata -- both `manifest.json` and `<id>.json` it still reference all the original layers even though only the new layers tarballs are present.  You can manually fix up the manifest.json (layer filenames) and the `<id>.json` (sha256 hashes at the end of each `layer.tar`, and then deleting/changing enough history entries to match the number of non-empty layers), and then it'll work with `docker load`.   But at that point you may as well have done everything manually.

**Comment by JavaChr1s** [comment]
I think @vvuk is right. :-(

**Comment by zot** [comment]
This works for me without using docker-squash:

1. Make a container that changes the image as in the normal docker-squash instructions
2. use `docker export CONTAINER-ID | docker import - REPOSITORY:TAG` to produce the squashed image

As far as I can tell, this produces an image similar to what docker-squash would produce.

**Comment by marcelser** [comment]
> This works for me without using docker-squash:
> 
> 1. Make a container that changes the image as in the normal docker-squash instructions
> 2. use `docker export CONTAINER-ID | docker import - REPOSITORY:TAG` to produce the squashed image
> 
> As far as I can tell, this produces an image similar to what docker-squash would produce.

No you're loosing all of with export/import:
ENV
ENTRYPOINT
LABEL
VOLUME

**Comment by hazcod** [comment]
@zot : That actually works perfect for my use case, thank you!
https://github.com/ironPeakServices/iron-debian/blob/master/.github/workflows/publish.yaml#L28
