### ISSUE TITLE
windows version is desired

### ISSUE THREAD

**Issue by zenglian** [jwilder/docker-squash#74]
Release for windows 10 x64 is desired.

**Comment by zot** [comment]
This works for me without using docker-squash:

1. Make a container that changes the image as in the normal docker-squash instructions
2. use `docker export CONTAINER-ID | docker import - REPOSITORY:TAG` to produce the squashed image

As far as I can tell, this produces an image similar to what docker-squash would produce.

**Comment by viceice** [comment]
I get `Error response from daemon: the daemon on this operating system does not support exporting Windows containers` on my windows 10 20H2.
