### ISSUE TITLE
ERROR: mkdir /tmp/docker-squash169074396/usr/lib/perl5/5.8.8/pod: file exists

### ISSUE THREAD

**Issue by xfgavin** [jwilder/docker-squash#76]
Hi there,

Thanks for the great tool.

I am using current release on Mac2016. I issued cmd below
sudo /Users/xfgavin/Downloads/docker-squash -i aaaa_20171003.tar -o aaaa_20171003_squashed.tar
but I got the error everytime
ERROR: mkdir /tmp/docker-squash169074396/usr/lib/perl5/5.8.8/pod: file exists

**Comment by paralin** [comment]
+1

:(

**Comment by nlgranger** [comment]
Same issue here, is there any way to make tar ignore these errors?
