### ISSUE TITLE
Does it ever end?

### ISSUE THREAD

**Issue by mastef** [jwilder/docker-squash#78]
```
USER  PID    %CPU %MEM       VSZ   RSS   TT  STAT STARTED      TIME COMMAND
root  76693  62.8  0.0 573380140  2200 s001  R+    5:34PM 694:26.59 docker-squash -i image.tar -o squashed.tar
root  76691   0.0  0.0   2498448  7648 s001  S+    5:34PM   0:00.05 sudo docker-squash -i image.tar -o squashed.tar
```

Started yesterday at 5pm, it's now the next day 12pm here. How come it's so slow? Are there ways to monitor if it's stuck? It seems this is a common issue, since the article that recommends docker squash, actually [also mentions that it didn't complete for them](https://blog.codacy.com/five-ways-to-slim-your-docker-images-5f4bd68d29f1).

Is `docker-squash` now obsolete after the introduction of `docker squash`?

**Comment by davidalbertonogueira** [comment]
Same, takes forever and it consumes all the disk space (many times more than the original image).
