### ISSUE TITLE
/usr/local/bin/docker-squash: cannot execute binary file

### ISSUE THREAD

**Issue by Claywd** [jwilder/docker-squash#79]
Just tried to do a basic squash and it of course wouldn't let me. Odd error that seems undocumented.

**Comment by rzr** [comment]
it looks like this project is no more active ? am i wrong ? if inactive can you suggest any alternative ?

**Comment by TuSKan** [comment]
macOS or Linux?

**Comment by Claywd** [comment]
MacOS

**Comment by TuSKan** [comment]
Wrong file. 
Use this https://github.com/jwilder/docker-squash/releases/download/v0.2.0/docker-squash-darwin-amd64-v0.2.0.tar.gz
